config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "islands/:id/edit", to: "islands#edit"
  patch "islands/:id", to: "islands#update"
  get 'islands/myisland', to: 'islands#myisland', as: 'myislands'
  get 'bookings/:id/book_recap', to: 'bookings#book_recap', as: 'book_recap'

  resources :islands do
    resources :bookings, only: [:new, :create, :edit, :update]
  end
  resources :bookings, only: [:index, :show, :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :continent, inclusion: { in: ['Asie', 'Amérique du Nord', 'Amérique du Sud', 'Europe', 'Afrique', 'Océanie']}
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :islands, dependent: :destroy
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :city, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :city, :date_of_birth, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :find_booking, only: [:show, :edit, :update, :destroy]
skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def index
    @bookings = current_user.bookings
    @islands = []
    @user_bookings = @bookings.where(user_id: current_user.id)
    @user_bookings.each do |booking|
      @islands << [Island.where(id: booking.island_id), booking]
    end
    @user = User.new
    flash[:notice] = "Votre réservation a bien été prise en compte" if params[:booking] == "true"
  end

  def new
    @booking = Booking.new
  end

  def show
  end

  def create
    @booking = Booking.new(params_booking)
    @booking.island_id = params[:island_id]
    @booking.user = current_user
    if @booking.save
      redirect_to book_recap_path(Booking.last)
    else
      render :new
    end
  end

  def book_recap
    @booking     = Booking.find(params[:id])
    @days         = (@booking.check_out_date - @booking.check_in_date).to_i
    @island      = @booking.island
    @total_price = @island.price_per_day * (@days)
    # redirect_to bookings_path
  end

  def edit
  end

  def update
    @booking.update(params[:booking])
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
  end

  private

  def params_booking
    params.require(:booking).permit(:check_in_date, :check_out_date)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :find_island, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def index
    p params
    p params[:continent].present?
    if params[:continent].present?
      keyword_search = CONTINENT_CARD[params[:continent].to_sym][:name]
      @picture = CONTINENT_CARD[params[:continent].to_sym][:image_path]
      @islands = Island.where("continent ILIKE ?", "%#{keyword_search}%")
    else
      @islands = Island.all
    end
  end

  def myisland
    @islands = Island.where( user: current_user)
  end

  def show
    @island = Island.find(params[:id])
    @booking = Booking.new
    @user = @island.user
    @markers = [
      {
        lat: @island.latitude,
        lng: @island.longitude,
        image_url: helpers.asset_url('palmtree.png')
      }
    ]
    @price = 10
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user
    p @island.save!
    if @island.save
      redirect_to islands_path(continent: "#{@island.continent.parameterize.underscore}")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @island.update(island_params)
      redirect_to island_path(@island)
    else
      render :edit
    end
  end

  def destroy
    @island = Island.find(params[:id])
    @island.destroy
    redirect_to myislands_path
  end

  private

  def find_island
    @island = Island.find(params[:id])
  end

  def island_params
    params.require(:island).permit(:name, :description, :address, :continent, :availability, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def home
    @island = Island.new
    @islands = Island.all
    @user = User.new
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/book_recap.html.erb
<div class="wrapper">
  <div class="container">
  <h1 class="page-title">A propos de votre voyage :</h1>
    <div class=" d-flex justify-content-center row">
      <div class="col-md-8 col-sm-6">
        <div class="ticket-card">
          <div class="cover">
            <img src=<%= @island.photo %> />
          </div>

          <div class="body">
            <div class="artist">
              <h6 class="info"><i class="fa fa-map-marker"></i><%= @island.continent %></h6>
              <h4 class="name">Ile <%= @island.name %></h4>
            </div>
            <div class="price">
              <div class="from">Prix par jour: </div>
              <div class="value price-island-per-day">
                <%= @island.price_per_day %><b>€</b>
              </div>
            </div>

            <div class="clearfix"></div>
            <div class="info">
              <p><%= @island.description %></p>
              <div class="period-of-stay d-flex justify-content-between">
                <p><i class="fa fa-calendar"></i> <%= @booking.check_in_date.strftime("%e %B %Y")%></p>
                <i class="fas fa-arrow-right"></i>
                <p><i class="fa fa-calendar"></i><%= @booking.check_out_date.strftime("%e %B %Y") %></p>
              </div>
              <div class="d-flex justify-content-between number-of-days">
                <p class="days">Nombre de jours : </p>
                <p class="days-total"> <%= @days %> </p>
              </div>
              <div class="d-flex justify-content-between total-price-of-reservation">
                <p>Montant total de votre réservation : </p>
                <p class="total-price-island"> <strong><%= @total_price %><span>€</span></strong>  </p>
              </div>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="footer">
          <%= link_to "Accédez à vos réservations", bookings_path(booking: true), class: 'btn toggle-tickets validation-reservation' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1 class="margin next-holidays">Mes prochaines vacances :</h1>
<br>

<div class="container design-card">
  <div class="d-flex justify-content-center">
    <div class="col-md-9">
      <%= render 'shared/cardbooking', islands: @islands %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/islands/destroy.html.erb
<h1>Islands#destroy</h1>
<p>Find me in app/views/islands/destroy.html.erb</p>

app/views/islands/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="margin create-island-form">Mettez à jour votre île</h1>

      <%= simple_form_for @island do |f| %>
        <%= f.input :name %>
        <%= f.input :description, as: :text, :input_html => {:maxlength => 250 }%>
        <%= f.input :continent, collection: ["Afrique", "Asie", "Amérique du Sud", "Amérique du Nord", "Océanie", "Europe"] %>
        <%= f.input :availability, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.input :price_per_day, as: :integer %>
        <%= f.input :address, as: :string %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/islands/index.html.erb
<% if params[:continent].present? %>
  <div class="banner" style= "background-image: url('<%= @picture %>')">
    <h1 class="set-continent"> Îles en <%= @islands.first.continent %></h1>
  </div>
<% end %>

<%= link_to "retour", root_path, class:'btn btn-ghost', style: 'margin: 20px'%>

<div class="container design-card">
  <div class="d-flex justify-content-center">
    <div class="col-md-9">
      <% @islands.each do |island| %>
        <%= render 'shared/card_product', island: island %>
      <% end %>
    </div>
  </div>
</div>

app/views/islands/myisland.html.erb
<% @islands.inspect %>
<div class="container design-card">
  <div class="d-flex justify-content-center">
    <div class="col-md-9">
      <% @islands.each do |island| %>
        <%= render 'shared/card_product', island: island %>
      <% end %>
    </div>
  </div>
</div>

app/views/islands/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="margin create-island-form">Partagez votre île</h1>

      <%= simple_form_for @island do |f| %>
        <%= f.input :name %>
        <%= f.input :description, as: :text, :input_html => {:maxlength => 250 }%>
        <%= f.input :continent, collection: ["Afrique", "Asie", "Amérique du Sud", "Amérique du Nord", "Océanie", "Europe"] %>
        <%= f.input :availability, as: :boolean, checked_value: true, unchecked_value: false %>
        <%= f.input :price_per_day, as: :integer %>
        <%= f.input :address, as: :string %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/islands/show.html.erb
<div class="banner" style="background-image: url(<%= @island.photo %>)">
</div>
<%= link_to "retour", :back, class:'btn btn-ghost', style: 'margin: 30px'%>
<div class="card-owner-island">
  <%= cl_image_tag @island.user.photo, class: "avatar-show", alt: "avatar-large" %>
  <%#= image_tag('photo_avatar.jpg',
  <%#= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar-show", alt: "avatar-large" %>
  <p class="set-name" ><%= @island.user.first_name %></p>
</div>
<div>
</div>
<div class="container">
  <div class="d-flex flex-row">
    <div class="col-md-6">
      <h1><%= @island.name %></h1>
      <p style=“font-style: italic”><%= @island.price_per_day %> € / jour</p>
      <div id="price-per-day" class="d-none"><%= @island.price_per_day %></div>
      <br>
      <p>Située en <span class="span-blue"><%= @island.continent %></span></p>
      <p><%= @island.description %></p>
    </div>
    <div class="col-md-6">
      <div class="map-style"
        id="map"
        style="width: 100%;
        height: 300px;
        box-shadow: 0 0 15px rgba(0,0,0,0.1);
        margin-top: 35px;
        border-radius: 15px;
        margin-bottom: 35px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
      <div>
        <%= simple_form_for [@island, @booking] do |f| %>
          <%= f.input :check_in_date, class: 'departure', label: "Date d'arrivée :" %>
          <%= f.input :check_out_date, class: 'arrival', label: "Date de départ :" %>
          <div class="d-flex justify-content-between">
            <p>Nombre de jours : </p>
            <div id="total-days"></div>
          </div>

          <div class="d-flex justify-content-between">
            <p>Total : </p>
            <div id="total-price"></div>
          </div>

          <%= f.button :submit, "Réserver", class: 'btn btn-primary reserve-button', style: 'margin-bottom: 30px' %>
        <% end %>
        <br>
      </div>
    </div>
  </div>
</div>
<div>
  <div data-set="<%= @price %>"></div>
  <div data-set="<%= @days %>"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title>IslandBnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="min-width-container"><%= yield %></div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1527401850656-0f34108fdb30?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>Tentez l'expérience du <span class="italic">bout du monde...</span></h1>
    <p>...Offrez-vous le séjour de vos rêves !</p>
  </div>
</div>

<div class="container">
  <div class="home-form">
    <h2 class="container">Réservez une île et une expérience unique</h2>
    <hr style="margin-left: 15px">
    <br>
    <div class="row">
      <% CONTINENT_CARD.each do |continent| %>
        <%= render 'shared/card_continent', continent: continent %>
      <% end %>
    </div>
  </div>


   <!-- SECOND CODE FOR THE SEARCH BAR => BETTER ONE
      <div class="flash flash-success fade show">
    < simple_form_for @island, method: :get do |f| %>
      <div class="form-row">
        <div class="col-6 form-group">
        <= f.input :continent,  label: false, collection: ["Afrique","Amérique du Nord","Amérique du Sud","Asie","Europe","Océanie"], prompt: "Select your continent" %>
        </div>
        <div class="col-6 form-group">
        <= f.submit "rechercher" %>
        </div>
      </div>
      <end%>




   codes for search bar:

   <form>
      <div class="form-row col-md-12">
        <div class="form-group col-md-4">
          <label for="inputContinent">OÙ</label>
          <select id="inputState" class="form-control">
          </select>
        </div>
        <div class="form-group col-md-3">
          <label for="inputArrival">ARRIVÉE</label>
          <input type="date" class="form-control" id="inputdeparturedate" placeholder="Password">
        </div>
        <div class="form-group col-md-3">
          <label for="inputDeparture">DEPART</label>
          <input type="date" class="form-control" id="inputarrivaldate" placeholder="Password">
        </div>
        <div class="form-group col-md-2">
          <label for="inputNumber">VOYAGEURS</label>
          <input type="number" class="form-control" id="inputNumber" placeholder="Nombre">
        </div>
      </div>
      <button type="submit" class="btn btn-primary" style="margin-left: 15px">Rechercher</button>
    </form>
  </div>
</div> -->

app/views/shared/_card_continent.html.erb
<div class="col-sm-4">
  <%= link_to islands_path(continent: continent[0]) do %>
    <div class="card-continent my-3">
      <div class="card-body d-flex justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= continent[1][:image_path] %>)">
        <div class="continent-name"><%= continent[1][:name] %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_card_product.html.erb
  <div class="card-product my-3">
    <%= cl_image_tag island.photo %>
    <div class="card-product-infos">
      <h2><%= link_to island.name, island_path(island) %> </h2>
      <p><%= island.description %> </p>
      <p> <%= island.price_per_day %> € / jour</p>
      <div class="d-flex justify-content-between">
        <p> <%= island.user.first_name %></p>
        <div class="d-flex">
          <% if  current_user == island.user %>
            <div class="button mx-3">
              <%= link_to "Delete", island, method: :delete%>
            </div>
            <div class="button">
              <%= link_to "Update", edit_island_path(island), method: :get%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_cardbooking.html.erb
<% islands.each do |island| %>
  <div class="card-product my-3">
      <%= cl_image_tag island[0][0].photo, alt: "alttext" %>
    <div class="card-product-infos">
      <h2><%= link_to island[0][0].name, "" %></h2>
      <p><%= island[0][0].description %> </p>
     <p><%= island[1].check_in_date %></p>
      <p><%= island[1].check_out_date %></p>
    </div>
  </div>
<% end %>

app/views/shared/_cardproduct.html.erb
<% @islands.each do |island| %>
  <div class="card-product my-3">
    <img src=<%= island.photo %> />
    <div class="card-product-infos">
      <h2><%= link_to island.name, island_path(island) %> </h2>
      <p><%= island.description %> </p>
      <p> <%= island.price_per_day %> € / jour</p>
      <p> <%= island.user.first_name %></p>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-components">
    <a class="apn" href="/A Propos de nous">A propos de nous </a>
    <a class="faq" href="/FAQ">FAQ </a>
    <a class="pec" href="/Politique et confidentialité">Politique et confidentialité </a>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <a href="<%= root_path %>" title="Home" class="signature">IslandBnb</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Créer une annonce", new_island_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%#= image_tag('photo_avatar.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mes bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Mes annonces", myislands_path, class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Inscription", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>